backend/models/Menu.php
<?php
namespace backend\models;

use Yii;
use yii\web\IdentityInterface;
use yii\db\ActiveRecord;
use yii\base\Module;

class Menu extends ActiveRecord
{
    
    public static function tableName()
    {
        return '{{%pro_menu}}';
    }
    
    public function rules() {
        return [
            [['name'],'required'],
            [['is_show'],'required'],
            [['url'],'default','value'=>''],
            [['weight'],'number'],
            [['parent_id'],'default','value'=>0],
            [['name'], 'string', 'max' => 18],
            [['channel'], 'required']
        ];
    }
    
    public function attributeLabels()
    {
        return array(
            'name'      => '名称',
            'mark'      => 'MARK',
            'url'       => 'url路径',
            'parent_id' => '所属分类',
            'weight'    => '排序',
            'is_show'   => "是否显示",
            'channel'   => "所属系统"
        );
    }
    
    /**
     * 返回是否显示
     * @author  li
     * @since   2015-09-23
     */
    public static function display() {
        return array(
            0 => '不显示',
            1 => '显示'
        );
    }
    
    /**
     * 获取模板列表
     * @author  li
     * @since   2015-05-18
     */
     public function moduleList() {
         $ids = [];
         $data = Menu::find()->orderBy('channel desc')->where(['parent_id'=>0,'is_show'=>1])->asArray()->all();
         foreach ($data as $value) {
             $ids[] = $value['id'];
         }
         $find = Menu::find()->where(['parent_id'=>$ids])->asArray()->all();
         
         foreach ($data as $key=>$value) {
             foreach ($find as $val) {
                 if($value['id']==$val['parent_id']) {
                     $data[$key]['find'][] = $val;
                 }
             }
         }
         return $data;
     }
     
     /*
      * 获取父级菜单
      */
     public static function getParent($channel) {
         $mArr = [];
         $data = Menu::find()->where(['parent_id' => 0, 'channel' => $channel])->all();
         $mArr[0] = '一级菜单';
         foreach ($data as $v) {
             $mArr[$v['id']] = $v['name'];
         }
         return $mArr;
     }

    public static function getChannel($id)
    {
        return Menu::find()->where(['id' => $id])->one();
    }
    
}

backend/controllers/MenuController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use backend\models\Menu;
use common\models\Helper;

/**
 * Site controller
 */
class MenuController extends BaseController
{

    /**
     * 模块显示
     *
     * @author li
     * @since 2015-4-18
     */
    public function actionList()
    {
        $module = new Menu();
        $data = $module->moduleList();
        
        return $this->render('index', [
            'menu' => $data
        ]);
    }

    /**
     * 填加模块
     */
    public function actionAdd()
    {

        $menu = new Menu();
        if ($menu->load($post = Yii::$app->request->post())) {
            $menu->created_at = $menu->update_at = time();
            if ($menu->save()) {
                return $this->redirect('/menu/list');
            }
        }

        // var_dump($menu);die;
        $firstMenu = Menu::find()->where([
            'parent_id' => 0,
            'is_show' => 1,
            'channel' => 'admin'
        ])
            ->select('id,name')
            ->asArray()
            ->all();
        $t[0]['id'] = '0';
        $t[0]['name'] = '一级分类';

        $arr = array_merge($t, $firstMenu);
        return $this->render('add', [
            'model' => $menu,
            'menu' => $arr
        ]);
        
    }

    /**
     * 修改模块
     *
     * @author li
     * @since 2015-05-22
     *       
     */
    public function actionEdit()
    {
        $model = new Menu();
        $id = Yii::$app->request->get('id', 0);
        if ($id != 0) {
            $model = $model->findOne(['id' => $id]);
            //var_dump($model);die;
//            print_r(Yii::$app->request->post());die;
            if ($model->load(Yii::$app->request->post())) {
                if ($model->save()) {
                    return $this->redirect("/menu/list");
                }
            }
            return $this->render("edit", [
                'model' => $model,
                'id'    => $id
            ]);
        }
        return $this->redirect("/menu/list");
    }

    public function actionAjaxParentid()
    {
        $channel = Yii::$app->request->post('channel');
        $firstMenu = Menu::find()->where([
            'parent_id' => 0,
            'is_show' => 1,
            'channel' => "$channel"
        ])->asArray()->all();
        //var_dump($channel);die;
        $html = "<option value='0'>一级分类</option>";
        foreach($firstMenu as $v)
        {
            $html .= "<option value='". $v['id'] ."'>". $v['name'] ."</option>";
        }
        echo $html;
    }
}

backend/views/menu/add.php
<?php
use yii\bootstrap\ActiveForm;
use backend\models\Menu;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
?>
<script src="/js/jquery-1.7.1.min.js" type="text/javascript"></script>
<script src="/js/myForm.js" type="text/javascript"></script>
<style>
    #menu-is_show .radio{float:left;}
    #menu-is_show .radio:nth-of-type(2){margin-top: 10px;}
</style>

<ul class="breadcrumb">
	<li>
		<a href="/">首页</a>
		<span class="divider">/</span>
	</li>
	<li class="active">添加菜单</li>
</ul>

<?php
    $form = ActiveForm::begin([
        'id' => 'active-form',
        'action' => '/menu/add',
        'options' => [
            'class' => 'form-signin',
            'enctype' => 'multipart/form-data'
        ],
    ]);

?>

<div class="container-fluid">
	<div class="row-fluid">

		<div class="well">
            <label class="control-label">所属系统</label>
            <div>
                <?php
                echo Html::activeDropDownList($model, 'channel', ArrayHelper::map([ 0 => ['id' => 'admin', 'name' => '后台管理系统'],  1 => ['id' => 'yunying', 'name' => '运营管理系统'], 2 => ['id' => 'config', 'name' => '配置后台'], 3 => ['id' => 'article', 'name' => '官网后台']],'id', 'name'), ['style' => 'width: 220px;height: 40px;border-radius: 5px;box-shadow: 0 0 5px #ccc;position: relative;']);
                ?>

            </div>
        <label class="control-label">所属分类</label>
            <div>
                <?php
                 echo Html::activeDropDownList($model, 'parent_id', ArrayHelper::map($menu,'id', 'name'), ['style' => 'width: 220px;height: 40px;border-radius: 5px;box-shadow: 0 0 5px #ccc;position: relative;']);
                ?>
            </div>
            <div id='name'><?= $form->field($model,'name')->input('text',['style'=>'width: 220px;height: 30px;']); ?></div>

            <div id='url'><?= $form->field($model,'url')->input('text',['style'=>'width: 220px;height: 30px;']); ?></div>
            <div id='weight'><?= $form->field($model,'weight')->input('text',['style'=>'width: 220px;height: 30px;']); ?></div>
            <div id='display'><?= $form->field($model,'is_show')->radioList(Menu::display(),[]); ?></div>
        </div>

        <div class="btn-toolbar">
            <button class="btn btn-primary" name="button" value="tj">
				
				<i class="icon-save"></i>保存</button>
            <a href="/menu/list" data-toggle="modal" class="btn">取消</a>
            <div class="btn-group"></div>
        </div>
        	 
    </div>        
</div>

<?php ActiveForm::end(); ?>
<div class="modal small hide fade" id="message" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">提示</h3>
    </div>
    <div class="modal-body">
        <p class="error-text"><i class="icon-warning-sign modal-icon"></i><span>删除成功</span></p>
    </div>
    <div class="modal-footer">
         <button class="btn cancel" data-dismiss="modal" aria-hidden="true">确定</button>
    </div>
</div>

<script>
$(function(){
	<?php if(Yii::$app->session->hasFlash('message')):?>
    $('#message').modal('show');
    $('.error-text span').html('<?php echo Yii::$app->session->getFlash('message');?>');
	<?php endif;?>
});
$("#parentid").change(function() {
    var parent_id = $("#parentid").val();
    if(parent_id == 0){
        $("#mark").show();
        $("#weight").show();
        $("#url").hide();
    }
    else
    {
        $("#mark").hide();
        $("#weight").hide();
        $("#url").show();
    }
});

$(function() {
    var parent_id = $("#parentid").val();
    if(parent_id == 0)
    {
        $("#mark").show();
        $("#weight").show();
        $("#url").hide();
    }else
    {
        $("#mark").hide();
        $("#weight").hide();
        $("#url").show();
    }
});
    $('#menu-channel').change(function()
    {
        $.ajax({
            url: "/menu/ajax-parentid",
            type: "post",
            //dataType: "json",
            data: {'channel': $(this).val()},
            success: function (data) {
                $('#menu-parent_id').html(data);
            }
        })
    })

</script>

backend/views/menu/edit.php
<?php
use yii\bootstrap\ActiveForm;
use backend\models\Menu;

?>
<link rel="stylesheet" type="text/css" href="/css/bootstrap.css">
<link rel="stylesheet" href="/css/font-awesome.css">
<script src="/js/jquery-1.7.1.min.js" type="text/javascript"></script>
<script src="/js/myForm.js" type="text/javascript"></script>
<style>
    #menu-is_show .radio{float:left;}
    #menu-is_show .radio:nth-of-type(2){margin-top: 10px;}
</style>

<ul class="breadcrumb">
	<li>
		<a href="/">首页</a>
		<span class="divider">/</span>
	</li>
	<li class="active">编辑菜单</li>
</ul>

<?php
    $form = ActiveForm::begin([
        'id' => 'active-form',
        'action' => "/menu/edit?id=$id",
        'options' => [
            'class' => 'form-signin',
            'enctype' => 'multipart/form-data'
        ],
    ]);
$channel = Yii::$app->redis->get('channel_'.Yii::$app->user->getIdentity()->id);
?>

<div class="container-fluid">
	<div class="row-fluid">

		<div class="well">
            <div id='parent_id'>
                <?php if($model->parent_id == 0):?>
                    <?= $form->field($model,'parent_id')->dropDownList( [0 => '一级菜单'],['style'=>'width: 220px;height: 34px;']); ?>
                <?php else:?>
                    <?= $form->field($model,'parent_id')->dropDownList( Menu::getParent($model->channel),['style'=>'width: 220px;height: 34px;']); ?>
                <?php endif;?>
            </div>
            <div id='name'><?= $form->field($model,'name')->input('text',['style'=>'width: 220px;height: 30px;']); ?></div>
            <div id=''><?= $form->field($model,'url')->input('text',['style'=>'width: 220px;height: 30px;']); ?></div>
            <div id='weight'><?= $form->field($model,'weight')->input('text',['style'=>'width: 220px;height: 30px;']); ?></div>
            <div id='display'><?= $form->field($model,'is_show')->radioList(Menu::display(),[]); ?></div>
        </div>

        <div class="btn-toolbar">
            <button class="btn btn-primary" name="button" value="tj">
				<i class="icon-save"></i>保存</button>
            <a href="/menu/list" data-toggle="modal" class="btn">取消</a>
            <div class="btn-group"></div>
        </div>
    </div>
</div>

<?php ActiveForm::end(); ?>

<div class="modal small hide fade" id="message" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">提示</h3>
    </div>
    <div class="modal-body">
        <p class="error-text"><i class="icon-warning-sign modal-icon"></i><span>删除成功</span></p>
    </div>
    <div class="modal-footer">
         <button class="btn cancel" data-dismiss="modal" aria-hidden="true">确定</button>
    </div>
</div>

<script>
$(function(){
	<?php if(Yii::$app->session->hasFlash('message')):?>
    $('#message').modal('show');
    $('.error-text span').html('<?php echo Yii::$app->session->getFlash('message');?>');
	<?php endif;?>
});
$("#parent_id").change(function() {
    var parent_id = $("#parent_id").val();
    if(parent_id == 0){
        $("#mark").show();
        $("#weight").show();
        $("#url").hide();
    }
    else
    {
        $("#mark").hide();
        $("#weight").hide();
        $("#url").show();
    }
});

$(function() {
    var parent_id = $("#parent_id").val();
    if(parent_id == 0)
    {
        $("#mark").show();
        $("#weight").show();
        $("#url").hide();
    }else
    {
        $("#mark").hide();
        $("#weight").hide();
        $("#url").show();
    }
});

</script>

backend/views/menu/index.php
<?php
use yii\bootstrap\ActiveForm;
?>
<ul class="breadcrumb">
    <li><a href="/">首页</a> <span class="divider">/</span></li>
    <li class="active">城市列表</li>
</ul>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="btn-toolbar">
            <a href="/menu/add"><button class="btn btn-primary" style="margin-bottom:15px;"><i class="icon-plus"></i>新增菜单</button></a>
</div>

<div class="well">
    <table class="table table-bordered table-hover definewidth m10">

        <thead>
            <tr>
                <th>所属系统</th>
                <th>模块名称</th>
                <th>下级菜单</th>
                <th>操作</th>
            </tr>
        </thead>

        <?php foreach ($menu as $key => $value) :?>

            <tr>
                <td><?php if($value['channel'] == 'admin'):?>后台管理系统<?php elseif($value['channel'] == 'yunying'):?>运营管理系统<?php elseif($value['channel'] == 'config'):?>配置后台<?php else:?>官网后台<?php endif;?></td>
                <td><?=$value['name'];?></td>
                <td>
                <?php if(isset($value['find'])):?>
                     <?php foreach ($value['find'] as $val):?>
                     <ol style="margin: 10px 15px;">
                         <?php echo $val['name']."(".$val['url'].")";?>
                         <a href="/menu/edit?id=<?=$val['id']?>">编辑</a>
                     </ol>
                     <?php endforeach;?>
                     <?php endif;?>
                </td>
                <td>
                     <a href="/menu/edit?id=<?=$value['id']?>">编辑</a>
                </td>
            </tr>
        <?php endforeach;?>

    </table>
</div>

<div class="pagination">
    <ul>

    </ul>
</div>

<div class="modal small hide fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">删除确认</h3>
    </div>
    <div class="modal-body">
        <p class="error-text"><i class="icon-warning-sign modal-icon"></i>您真的要删除码？</p>
    </div>
    <div class="modal-footer">
        <button class="btn cancel" data-dismiss="modal" aria-hidden="true">取消</button>
        <button class="btn btn-danger" data-dismiss="modal">确定</button>
    </div>
</div>

<script type="text/javascript">
//删除城市
$(function(){
    var id = 0;
    $('.btn-danger').click(function(){
        $.getJSON('/city/delete',{'id':id},function(json){
              if(json.status==1){
          	       document.location.reload(true);
              }
              else{
                  alert(json.message);
              }
         });
        return false;
    });
    
    $('.del').click(function(){
        id =$(this).attr('id');
    });
    
});
</script>   
<script type="text/javascript">
//还原城市
$(function(){
	   var id = 0;
        $('.btn-danger').click(function(){
            $.getJSON('/city/recovery',{'id':id},function(json){
                  if(json.status==1){
              	       document.location.reload(true);
                  }
                  else{
                      alert(json.message);
                  }
             });
            return false;
        });

        $('.recovery').click(function(){
            $("#myModalLabel").html("还原确认");
            $(".error-text").html("<i class='icon-warning-sign modal-icon'></i>您真的要还原码？");
            id =$(this).attr('id');
        });
});
</script>                            